name: checking pods
on:
  push:
    branches:
      - 'master'

env:
  report: report.log
  fail_pods_report: fail_pods_report.log

jobs:
  my:
    runs-on: ubuntu-latest

    steps:
      - name: Connection to host
        run: |
          which ssh-agent
          mkdir ~/.ssh
          eval `ssh-agent -s`
          ssh-add - <<< "${{secrets.SSH_KEY}}"
          ssh-keyscan -H 178.124.206.53 >> ~/.ssh/known_hosts
          ssh jump_sa@178.124.206.53 ssh-keyscan192.168.203.14 >> ~/.ssh/known_hosts
          ssh -o ProxyCommand="ssh -W %h:%p jump_sa@178.124.206.53" root@192.168.203.14 \
          kubectl get pods -A >> output      
      - name: Checking status of pods
        id: check
        run: |
           sed -i '/Running/d' ${{ env.report }} >> ${{ env.fail_pods_report }}
           sed -i '/Completed/d' ${{ env.report }} >> ${{ env.fail_pods_report }}
           echo "other_statuses=$(wc -l < ${{ env.report }})" >> $GITHUB_OUTPUT

      - name: Upload report
        if: steps.check.outputs.other_statuses > 1
        uses: actions/upload-artifact@v2
        with:
          path: ${{ env.report}}
      
      - name: slack Notification
        if: steps.check.outputs.other_statuses > 1
        uses: rtCamp/action-slack-notify@v2 
        env:
          SLACK_CHANNEL: test
          SLACK_TITLE: 'Status of pods'
          SLACK_MESSAGE: 'Check your pods! You have status different from "Running" and "Completed"'
          SLACK_USERNAME: ${{ github.repository }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}c