---
name: Checking pods
on: workflow_dispatch 
env:
  report: report.log
  fail_pods_report: fail_pods_report.log
jobs:
  my:
    runs-on: ubuntu-latest
    steps:
      - name: Connection to host
        run: |
           mkdir ~/.ssh
           eval `ssh-agent -s`
           ssh-add - <<< "${{ secrets.SSH_KEY }}" 
           ssh-keyscan ${{ secrets.PROXY_HOST }} >> ~/.ssh/known_hosts
           ssh ${{ secrets.PROXY_USERNAME }}@${{ secrets.PROXY_HOST}} ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts
           ssh -o ProxyCommand="ssh -W %h:%p ${{ secrets.PROXY_USERNAME }}@${{ secrets.PROXY_HOST }}" ${{ secrets.USERNAME }}@${{ secrets.HOST }} "kubectl get pods -A" >> ${{ env.report }}  
      - name: Checking status of pods
        id: check
        run: |
           sed -i '/Running/d' ${{ env.report }} >> ${{ env.fail_pods_report }}
           sed -i '/Completed/d' ${{ env.report }} >> ${{ env.fail_pods_report }}
           echo "other_statuses=$(wc -l < ${{ env.report }})" >> $GITHUB_OUTPUT

      - name: Upload report
        if: steps.check.outputs.other_statuses > 1
        uses: actions/upload-artifact@v2
        with:
          path: ${{ env.report}}
      
      - name: slack Notification
        if: steps.check.outputs.other_statuses > 1
        uses: rtCamp/action-slack-notify@v2 
        env:
          SLACK_CHANNEL: test
          SLACK_TITLE: 'Pods status'
          SLACK_MESSAGE: 'Bad pods"'
          SLACK_USERNAME: ${{ github.repository }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}