name: checking pods
on:
  push:
    branches:
      - 'master'

env:
  report: report.log
  fail_pods_report: fail_pods_report.log

jobs:
  my:
    runs-on: ubuntu-latest

    steps:
      - name: Connection to host
        run: |
          which ssh-agent
          mkdir ~/.ssh
          eval `ssh-agent -s`
          ssh-add - <<< "-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEAu7t6/DyaOGAbI3JnRw4mfZKzMGxluLADfM75aAn70xsNaE+vMJVF
GT/HkHu4UH0Ws7I0dTKI56tCgpfTgw6WWx07Q4uAHW2+0eGKzPfgAlvZLlVGM/hZ77wsyY
HQPDtRZGJMuFg2Cpe+8Ki1VTqI5FebVYlcLEhasU8yKVKd+YYyBxtYwGSF18HeTLntDrXm
k/rmYUbeT10i33t6pdjP5RQKqGf3XZoStHILXvgemSnj7OuccouG7qiqD/BTLS/Nrx8Ak9
zYaIAWrY6FlcEgDVmOT2RH1zUOZzOSplzBf+FlYZHwOFQ0c6LZGrtbRUuMgL6puwb1GXkb
ebbGRV2ZF9R4t0emn4PJxPRx7T9QBXy+CNdR119rCoSiZ4Bfh6J6O3Xe5Y+io6vKB3CoCd
GUSHruFbshclSOQd2/C0hwwUyNd64zplGCjeJOSZgL1WnIK1NF25KnlVr+pfSBBfLvOJzt
BGSoGB5JckzmiJLKJZ4vklPVZM4hNbdiYWzZoC5LAAAFgPTRHWz00R1sAAAAB3NzaC1yc2
EAAAGBALu7evw8mjhgGyNyZ0cOJn2SszBsZbiwA3zO+WgJ+9MbDWhPrzCVRRk/x5B7uFB9
FrOyNHUyiOerQoKX04MOllsdO0OLgB1tvtHhisz34AJb2S5VRjP4We+8LMmB0Dw7UWRiTL
hYNgqXvvCotVU6iORXm1WJXCxIWrFPMilSnfmGMgcbWMBkhdfB3ky57Q615pP65mFG3k9d
It97eqXYz+UUCqhn912aErRyC174Hpkp4+zrnHKLhu6oqg/wUy0vza8fAJPc2GiAFq2OhZ
XBIA1Zjk9kR9c1DmczkqZcwX/hZWGR8DhUNHOi2Rq7W0VLjIC+qbsG9Rl5G3m2xkVdmRfU
eLdHpp+DycT0ce0/UAV8vgjXUddfawqEomeAX4eiejt13uWPoqOrygdwqAnRlEh67hW7IX
JUjkHdvwtIcMFMjXeuM6ZRgo3iTkmYC9VpyCtTRduSp5Va/qX0gQXy7zic7QRkqBgeSXJM
5oiSyiWeL5JT1WTOITW3YmFs2aAuSwAAAAMBAAEAAAGAbSWgaHx3kaVWwfIm16oDeOjM46
9yKMG1FWBkozeCwQcucWI60f1HUlnBlmBIFgvUIh/O3gDGliL9JV5ObBkUE99X8Hpvvyxq
UC5Ye7j19YkfKRANI/QVnguC4pllz08RkFKSlm865Ee7jMIZw3an1lKVDlMxUtGyYPpRiL
LvA/8goP8mR51qL7oYm/VRPUdGyuyJ+y6v2+ajetmYwkne/Sn81FK2ACavD1hrAgkyCQzQ
5pNJv1Md3S4UyfWI9nGenc+GMe0Jvn25qPb0gr7Bv2WVfslYTwqjxDIjvoTMOsDh7qvSIm
ifRzXYG1ZhVgOQKd/OkNOZI3n+jvsnyLO/hQTfi6TK+gBF4+8eLJhFZ6IKDptTki1oy4UE
WoUMSXwhi6uZ1T6BZ9VnBnWMNrV7AW2M0DWT8D9rUBSbI03z7uOlsNtD+cgkhubD26DVey
dOmmnHNcvjQbp43gRqN3cix+wT+2W1CFMTeclOR75HlcgeNtxpTKRLu8XgBvVUuxvpAAAA
wHkkM6+a/tKgUdxm88jZ9k7ojmwpsJ//FHJGTck6PFsZvsYrNBAwsuW0eiUvOe4fEhXouK
05MKR5dRzH9j6FLga1dUTLIO12dmo+3r9fafIcO0SrSrIr5xDw4df8xIV66RbGDsnTGpAa
7zTxwFbDdMZTEKos2q57uYiRBgwA/i9YpGsg6RIyazuE3fK+RLD+DW8+Ml8Hod+6e2yfhj
6HhrgHOUS7uvsPznebQukyyZG4TQksqWY2hIg+c0BcctWbbAAAAMEA60g19a1HCclambjQ
kiCnXb+HHzP+Brv8I6nKFRaXnYcSpCGOJfT/ghJWMKk/ML4G6/fFWn4+erRQ9lkg4auOld
zAwlrnfWLSrMDmci0IHn0UAE6g0GBrybLdkosHihet28bnLReHSpG2bnJH0IkaOFVfs03R
ivU967cFR1q/wH/Uy4qOuIwYH/rpEbCoc8P3IHLlwAtipylnN4UmzkmLFyMp7/9Q0voMnR
ontJZGhtziOkOxC10LqN0gzSKVSWaVAAAAwQDMQ2QyMhilZAHVF5LHLXH1pdw9gYr2Wlks
YTXGPzD9Ie3bJMsHV296OjOj1m4nBeRAHZtEdK27HtV8Hkp7CEzQv2frwiBMrtK37hY/0R
p6cxJ7yhwQrzoaJ6rcWlbnteXtEcFJitPJH3WJOleDwt2FA3iQYTsk92Ep0MlCVQri0vBd
0gi/RwXUuU6kITAXa/UVRjt+bQ2Ei4lb+hxYqv7HopJW60tIqVCdBnSsmRbyJFrcrYuFM/
Euif8qrXMQaV8AAAAIcm9vdEB2bTEBAgM=
-----END OPENSSH PRIVATE KEY-----
"
          ssh-keyscan -H 178.124.206.53 >> ~/.ssh/known_hosts
          ssh jump_sa@178.124.206.53 ssh-keyscan192.168.203.14 >> ~/.ssh/known_hosts
          ssh -o ProxyCommand="ssh -W %h:%p jump_sa@178.124.206.53" root@192.168.203.14 \
          kubectl get pods -A >> output      
      - name: Checking status of pods
        id: check
        run: |
           sed -i '/Running/d' ${{ env.report }} >> ${{ env.fail_pods_report }}
           sed -i '/Completed/d' ${{ env.report }} >> ${{ env.fail_pods_report }}
           echo "other_statuses=$(wc -l < ${{ env.report }})" >> $GITHUB_OUTPUT

      - name: Upload report
        if: steps.check.outputs.other_statuses > 1
        uses: actions/upload-artifact@v2
        with:
          path: ${{ env.report}}
      
      - name: slack Notification
        if: steps.check.outputs.other_statuses > 1
        uses: rtCamp/action-slack-notify@v2 
        env:
          SLACK_CHANNEL: test
          SLACK_TITLE: 'Status of pods'
          SLACK_MESSAGE: 'Check your pods! You have status different from "Running" and "Completed"'
          SLACK_USERNAME: ${{ github.repository }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}c