name: Deploying minikube and KinD
on:
  - push
  - pull_request
jobs:
  deploy_minikube:
    runs-on: ubuntu-latest
    name: minikube
    steps:
    - name: Install minikube
      uses: medyagh/setup-minikube@master
    - name: check_info
      run: |
       echo -e "Nods:\n$(kubectl get pods -A)" >> minikube.log
       echo -e "Minikube version:\n$(kubectl version --short)" >> minikube.log
       echo -e "Spintime: $(date '+%s')-${{ steps.start.outputs.start }}" >> minikube.log
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
          path: minikube.log

  deploy_KinD:
    runs-on: ubuntu-latest
    name: KinD
    steps:
    - name: Install KinD
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: "v0.17.0"
    - name: check_info
      run: |
       echo -e "Nods:\n$(kubectl get pods -A)" >> kind.log
       echo -e "KinD version:\n$(kubectl version --short)" >> kind.log
       echo -e "Spintime: $(date '+%s')-${{ steps.start.outputs.start }}" >> Kind.log
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
          path: kind.log